import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F4F9F4" },
    headerBackground: {
        backgroundColor: colors.primaryGreen,
        alignItems: "center",
        paddingTop: 60,
        paddingBottom: 30,
    },
    pageTitle: {
        fontSize: 22,
        fontWeight: "bold",
        color: "white",
        marginBottom: 20,
    },
    avatarWrapper: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: "#FFFFFF",
        justifyContent: "center",
        alignItems: "center",
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        overflow: "hidden",
    },
    avatarImage: { width: 90, height: 90, resizeMode: "contain" },
    infoBar: {
        backgroundColor: "#2E7D32",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    currentUserText: { color: "#E8F5E9", fontSize: 12, marginBottom: 2 },
    petName: { fontSize: 18, fontWeight: "bold", color: "#FFFFFF" },
    switchUser: {
        fontSize: 14,
        color: "#FFFFFF",
        textDecorationLine: "underline",
    },
    section: { paddingHorizontal: 20, paddingTop: 25 },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: colors.textDark,
        marginLeft: 10,
    },
    medalsContainer: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    medalItem: { alignItems: "center", width: 80 },
    medalCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 8,
        elevation: 2,
    },
    medalText: {
        fontSize: 12,
        fontWeight: "600",
        color: colors.textDark,
        textAlign: "center",
    },
    emptyConquistasContainer: {
        alignItems: "center",
        paddingVertical: 20,
        gap: 10,
    },
    emptyConquistasText: {
        textAlign: "center",
        color: "#BDBDBD",
        fontSize: 14,
        lineHeight: 20,
    },
    verTodasButton: { marginTop: 12, alignItems: "center" },
    verTodasText: {
        fontSize: 14,
        color: colors.primaryGreen,
        fontWeight: "600",
        textDecorationLine: "underline",
    },
    planCard: {
        backgroundColor: "white",
        padding: 20,
        borderRadius: 20,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    planStatus: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#FFA000",
        marginBottom: 10,
    },
    planDescription: {
        fontSize: 14,
        color: colors.textGray,
        marginBottom: 15,
        lineHeight: 20,
    },
    bold: { fontWeight: "bold", color: colors.textDark },
    emptyText: {
        textAlign: "center",
        color: colors.textGray,
        marginVertical: 10,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: "white",
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 25,
        minHeight: 300,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: colors.textDark,
        marginBottom: 20,
        textAlign: "center",
    },
    userOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 15,
    },
    modalAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#F0F0F0",
    },
    userOptionText: {
        fontSize: 18,
        color: colors.textDark,
        marginLeft: 15,
        fontWeight: "500",
    },
    divider: { height: 1, backgroundColor: "#E0E0E0", marginVertical: 10 },
    addUserOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 15,
        justifyContent: "center",
    },
    addUserText: {
        fontSize: 16,
        color: colors.primaryGreen,
        fontWeight: "bold",
        marginLeft: 10,
    },
    dependentRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 10,
    },
    userOptionFlex: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    acoesRow: { flexDirection: "row", gap: 4 },
    acaoBotao: { padding: 8 },
    editModalContent: {
        backgroundColor: "white",
        borderRadius: 20,
        padding: 24,
        width: "85%",
        alignSelf: "center",
    },
    editInput: {
        borderWidth: 1,
        borderColor: "#E0E0E0",
        borderRadius: 12,
        paddingHorizontal: 15,
        height: 50,
        fontSize: 16,
        color: colors.textDark,
        marginTop: 12,
    },
    editBotoesRow: {
        flexDirection: "row",
        gap: 12,
        marginTop: 20,
    },
    editBotaoCancelar: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E0E0E0",
        alignItems: "center",
    },
    editBotaoCancelarText: { color: colors.textGray, fontWeight: "600" },
    editBotaoSalvar: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: colors.primaryGreen,
        alignItems: "center",
    },
    editBotaoSalvarText: { color: "white", fontWeight: "600" },
});