import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F9F9F9", paddingTop: 60 },
    headerTitle: {
        fontSize: 24,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: 20,
        color: colors.textDark,
    },
    filhoSeletorContainer: { paddingHorizontal: 20, marginBottom: 16 },
    filhoSeletorLabel: {
        fontSize: 13,
        color: colors.textGray,
        marginBottom: 8,
        fontWeight: "600",
    },
    filhoScroll: { flexDirection: "row" },
    filhoChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: "#E0E0E0",
        marginRight: 8,
    },
    filhoChipAtivo: { backgroundColor: colors.primaryGreen },
    filhoChipText: { fontSize: 14, fontWeight: "600", color: "#757575" },
    filhoChipTextAtivo: { color: "white" },
    toggleContainer: {
        flexDirection: "row",
        backgroundColor: "#E0E0E0",
        borderRadius: 15,
        marginHorizontal: 30,
        padding: 4,
        marginBottom: 20,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 8,
        alignItems: "center",
        borderRadius: 12,
    },
    activeToggle: { backgroundColor: "white", elevation: 2 },
    toggleText: { fontWeight: "600", color: "#757575" },
    activeToggleText: { color: colors.primaryGreen },
    dateNavigation: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
    },
    currentDate: {
        fontSize: 16,
        fontWeight: "bold",
        marginHorizontal: 20,
        color: colors.textDark,
    },
    chartWrapper: {
        alignItems: "center",
        backgroundColor: "white",
        marginHorizontal: 20,
        borderRadius: 20,
        paddingVertical: 20,
        elevation: 3,
        minHeight: 150,
        justifyContent: "center",
    },
    chart: { borderRadius: 16 },
    semDadosContainer: { alignItems: "center", paddingVertical: 20, gap: 10 },
    semDadosText: {
        textAlign: "center",
        color: "#BDBDBD",
        fontSize: 14,
        lineHeight: 20,
    },
    summaryCard: {
        backgroundColor: "white",
        margin: 20,
        marginBottom: 40,
        padding: 20,
        borderRadius: 20,
        elevation: 2,
    },
    summaryTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 15,
        color: colors.textDark,
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    summaryLabelRow: { flexDirection: "row", alignItems: "center" },
    summaryLabel: { color: "#757575" },
    summaryLabelAlerta: { color: "#E53935", fontWeight: "600" },
    summaryValue: { fontWeight: "bold", color: colors.textDark },
    summaryValueAlerta: { color: "#E53935" },
    alertaBanner: {
        position: "absolute",
        top: 60,
        left: 16,
        right: 16,
        backgroundColor: "#C62828",
        borderRadius: 16,
        padding: 16,
        elevation: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 10,
        zIndex: 999,
    },
    alertaBannerHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    alertaBannerTituloRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    alertaBannerTitulo: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    alertaItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 6,
    },
    alertaItemText: { color: "#FFCDD2", fontSize: 14 },
    alertaItemValor: { color: "#fff", fontWeight: "bold" },
    alertaBannerBotao: {
        marginTop: 12,
        backgroundColor: "rgba(255,255,255,0.2)",
        borderRadius: 10,
        paddingVertical: 8,
        alignItems: "center",
    },
    alertaBannerBotaoText: { color: "#fff", fontWeight: "bold", fontSize: 14 },
});