import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../theme/colors';
const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
    background: { flex: 1, resizeMode: "cover" },
    container: {
        flex: 1,
        alignItems: "center",
        paddingTop: 60,
        paddingHorizontal: 20,
    },
    healthCard: {
        backgroundColor: "rgba(255, 255, 255, 0.95)",
        width: "100%",
        borderRadius: 20,
        padding: 20,
        elevation: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        zIndex: 1,
    },
    petName: {
        fontSize: 22,
        fontWeight: "bold",
        color: colors.primaryGreen,
        textAlign: "center",
        marginBottom: 15,
    },
    barContainer: { marginBottom: 12, width: "100%" },
    barLabelRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 5,
    },
    barLabel: { fontSize: 12, fontWeight: "bold", color: colors.textDark },
    barValue: { fontSize: 12, fontWeight: "bold", color: colors.textGray },
    barBackground: {
        width: "100%",
        height: 12,
        backgroundColor: "#EEEEEE",
        borderRadius: 6,
        overflow: "hidden",
    },
    barFill: { height: "100%", borderRadius: 6 },
    petContainer: {
        position: "absolute",
        bottom: 0,
        width: "100%",
        alignItems: "center",
        marginBottom: 50,
    },
    pandaImage: {
        width: screenWidth * 0.7,
        height: screenWidth * 0.7,
        resizeMode: "contain",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalCard: {
        backgroundColor: "white",
        borderRadius: 28,
        padding: 32,
        alignItems: "center",
        width: screenWidth * 0.82,
        elevation: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
    },
    modalTitulo: {
        fontSize: 20,
        fontWeight: "bold",
        color: colors.textDark,
        marginBottom: 20,
        textAlign: "center",
    },
    iconCircle: {
        width: 90,
        height: 90,
        borderRadius: 45,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
        elevation: 4,
    },
    modalNome: {
        fontSize: 22,
        fontWeight: "bold",
        color: colors.primaryGreen,
        marginBottom: 8,
        textAlign: "center",
    },
    modalDescricao: {
        fontSize: 14,
        color: "#757575",
        textAlign: "center",
        lineHeight: 20,
        marginBottom: 24,
    },
    modalBotao: {
        backgroundColor: colors.primaryGreen,
        paddingHorizontal: 36,
        paddingVertical: 14,
        borderRadius: 25,
    },
    modalBotaoTexto: { color: "white", fontSize: 16, fontWeight: "bold" },
});